spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/delicious_food_recipes}
    username: root
    password: password
  messages:
    basename: messages
    encoding: UTF-8
logging:
  level:
    org:
      springframework: WARN